### ISSUE TITLE
怎么打成war包 部署到Tomcat上

### ISSUE THREAD

**Issue by ghl0903** [KongZouXiang/TradeSteward#1]
用的idea 编辑器  怎么打成war包 部署到Tomcat上

**Comment by KongZouXiang** [comment]
在pom.xml将jar改成war即可,不过没有特定需求不建议

**Comment by ghl0903** [comment]
> 在pom.xml将jar改成war即可,不过没有特定需求不建议

打成了 tradesteward.war  包 上传到 Linux服务器的Tomcat下的 webapps 目录下  启动Tomcat，生成了 tradesteward 文件，然后 访问 http://*.*.*.*:8080/tradesteward/    路径时 报404 错误，是我路径不对  还是 打包的时候错误

**Comment by KongZouXiang** [comment]
可以看一下tomcat启动日志,路径项目名可能不正确
